project_id = "qeobfzrzqtskfprcgtel"

[functions.milestone-predictions]
verify_jwt = false

[functions.recommend-products]
verify_jwt = true

[functions.preload-recommendations]
verify_jwt = false

[functions.generate-baby-image]
verify_jwt = true
